//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unixFormLab3.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unixFormLab3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap died {
            get {
                object obj = ResourceManager.GetObject("died", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eat {
            get {
                object obj = ResourceManager.GetObject("eat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fork {
            get {
                object obj = ResourceManager.GetObject("fork", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fork1 {
            get {
                object obj = ResourceManager.GetObject("fork1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hungry {
            get {
                object obj = ResourceManager.GetObject("hungry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hungry1 {
            get {
                object obj = ResourceManager.GetObject("hungry1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_1KFjpU4ZzY {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-1KFjpU4ZzY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_2jizz9fsLf {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-2jizz9fsLf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_3XDBnscjeD45w {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-3XDBnscjeD45w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_5vnKSOYs6w {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-5vnKSOYs6w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_6aCplNgdN2 {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-6aCplNgdN2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_6EzRQIeWzmeG {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-6EzRQIeWzmeG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_9pdY5UUhj4Z {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-9pdY5UUhj4Z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_AvOPKjbflX {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-AvOPKjbflX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_B1niFg2RvG5 {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-B1niFg2RvG5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_B6VRwrrCUXvF {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-B6VRwrrCUXvF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_bcUHCqXhcr {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-bcUHCqXhcr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_bcUHCqXhcr1 {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-bcUHCqXhcr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_FlBMvFTwplw {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-FlBMvFTwplw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_hgCahUvmVnAbP {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-hgCahUvmVnAbP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_hOz8s1ftaZXL {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-hOz8s1ftaZXL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_iog4J0abS9GGCn {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-iog4J0abS9GGCn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_iuoOIo1ExxH {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-iuoOIo1ExxH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_KHWTY0aF0cnb {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-KHWTY0aF0cnb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_mOQngtbXBb6mwKR {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-mOQngtbXBb6mwKR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_nNPu8mVF6rW3 {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-nNPu8mVF6rW3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_NvB3TrRNvB51R5z {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-NvB3TrRNvB51R5z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_nXDqbzKHPAmY {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-nXDqbzKHPAmY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_Q9hYP2JKFJ1tKSfZ {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-Q9hYP2JKFJ1tKSfZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_qe5Ey3jA8NmFY {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-qe5Ey3jA8NmFY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_S81vX1q2cFPV {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-S81vX1q2cFPV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_Sj09MvsLgmo7 {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-Sj09MvsLgmo7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_TfC28EXDQz4a {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-TfC28EXDQz4a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_utDcTFkoK7 {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-utDcTFkoK7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_xV8dhlMlrRD {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-xV8dhlMlrRD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_yjaJCwfy8bZ3zjL1 {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-yjaJCwfy8bZ3zjL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgonline_com_ua_Rotate_360_ZmTHga6NroT {
            get {
                object obj = ResourceManager.GetObject("imgonline-com-ua-Rotate-360-ZmTHga6NroT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ML_SpicyPeanutSaute_RiceNoodles_72dpi_rgb_OLO_OH_600x400 {
            get {
                object obj = ResourceManager.GetObject("ML_SpicyPeanutSaute-RiceNoodles_72dpi_rgb_OLO_OH-600x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ML_SpicyPeanutSaute_RiceNoodles_72dpi_rgb_OLO_OH_600x4001 {
            get {
                object obj = ResourceManager.GetObject("ML_SpicyPeanutSaute-RiceNoodles_72dpi_rgb_OLO_OH-600x4001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ML_SpicyPeanutSaute_RiceNoodles_72dpi_rgb_OLO_OH_600x4002 {
            get {
                object obj = ResourceManager.GetObject("ML_SpicyPeanutSaute-RiceNoodles_72dpi_rgb_OLO_OH-600x4002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noodle {
            get {
                object obj = ResourceManager.GetObject("noodle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap think {
            get {
                object obj = ResourceManager.GetObject("think", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap think1 {
            get {
                object obj = ResourceManager.GetObject("think1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap think2 {
            get {
                object obj = ResourceManager.GetObject("think2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
