//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewersFilm
    {
        public int vf_id { get; set; }
        public int vf_f_id { get; set; }
        public int vf_v_id { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Viewer Viewer { get; set; }
    }
}
