//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsLab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmsGenre
    {
        public int fg_id { get; set; }
        public int fg_f_id { get; set; }
        public int fg_g_id { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
